config/routes.rb
Job::Application.routes.draw do

 resources :posaos
 root "posaos#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posaos
end

app/models/posao.rb
class Posao < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posaos_controller.rb
class PosaosController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@posaos = Posao.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@posaos = Posao.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
	end

	def new
		@posao = Posao.new
	end

	def create
		@posao = Posao.new(posaos_params)

		if @posao.save
			redirect_to @posao
		else
			render "New"
		end
	end

	def edit

	end

	def update
		if @posao.update(posaos_params)
			redirect_to @posao
		else
			render "Edit"
		end
	end

	def destroy
		@posao.destroy
		redirect_to root_path
	end

	private

	def posaos_params
		params.require(:posao).permit(:title, :description, :company, :url, :category_id)		
	end

	def find_job
		@posao = Posao.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posaos_helper.rb
module PosaosHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Ruby on Rails Jobs
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand Rails Jobs
			%ul.nav.navbar-nav
				%li= link_to "All Jobs", root_path
				- Category.all.each do |category|
					%li= link_to category.name, posaos_path(category: category.name)
			= link_to "New Job", new_posao_path, class: "navbar-text navbar-right navbar-link"
	.container
		.col-md-6.col-md-offset-3
			= yield

app/views/posaos/_form.html.haml
= simple_form_for(@posao, html: { class: 'form-horizontal'}) do |f|
	= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}
	= f.input :title, label: "Job Title"
	= f.input :description, label: "Description"
	= f.input :company, label: "Company"
	= f.input :url, label: "URL"
	%br/
	= f.button :submit

app/views/posaos/edit.html.haml
%h1 Edit Job

= render 'form'

= link_to 'Back', root_path

app/views/posaos/index.html.haml
- @posaos.each do |posao|
	%h2= link_to posao.title, posao
	%p= posao.company

= link_to 'New Job', new_posao_path

app/views/posaos/new.html.haml
%h1 New Job

= render 'form'

= link_to 'Back', root_path

app/views/posaos/show.html.haml
%h1= @posao.title
%p= @posao.description
%p= @posao.company

= link_to 'Home', root_path
= link_to 'Edit', edit_posao_path
= link_to 'Delete', posao_path(@posao), method: :delete, data: { confirm: "Are you sure?"}